name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "modder-bot" #Must be unique in Heroku
          heroku_email: "blynblack@gmail.com"
          buildpack: "https://github.com/heroku/heroku-buildpack-python.git"
          procfile:  "worker: python app.py"
